### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by squidds** [demyxsh/code-server#8]
Just wondering. If so I will try to get the ZSH and fonts config moved over to one of the linuxserver images.

**Comment by demyxco** [comment]
Hi there, sorry for the super late reply. This project isn't abandoned. Any issues you're facing?

**Comment by demyxco** [comment]
Hi, I will be closing this issue since it's been stale for several months. Please feel free to open a new issue or come join us on our discord server.

https://demyx.sh/discord
